# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "imhotep"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julien Portalier"]
  s.date = "2013-05-06"
  s.description = "Wiki engine for Ruby on Rails."
  s.email = "ysbaddaden@gmail.com"
  s.files = [
    "lib/imhotep.rb",
    "lib/imhotep/config.rb",
    "lib/imhotep/controllers/pages_controller.rb",
    "lib/imhotep/models/page.rb",
    "lib/imhotep/routes.rb"
  ]
  s.homepage = "http://github.com/ysbaddaden/imhotep"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Wiki engine for Ruby on Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0"])
  end
end

